// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC70yblGuDF3JSTgejhlXHlMtiK737YrA',
    appId: '1:1044637791712:web:078a4c5c4c9583b2eca785',
    messagingSenderId: '1044637791712',
    projectId: 'ass5-q2',
    authDomain: 'ass5-q2.firebaseapp.com',
    databaseURL: 'https://ass5-q2-default-rtdb.firebaseio.com',
    storageBucket: 'ass5-q2.appspot.com',
    measurementId: 'G-ZF1WEYGCVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUp-GO9xpv3bPn4kNDRfE3qQZRLQBgnY',
    appId: '1:1044637791712:android:c16449720911f9f5eca785',
    messagingSenderId: '1044637791712',
    projectId: 'ass5-q2',
    databaseURL: 'https://ass5-q2-default-rtdb.firebaseio.com',
    storageBucket: 'ass5-q2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBik5WeXqfMsl14ZAN3TKru39vJR2xaB_E',
    appId: '1:1044637791712:ios:601289bf093ab99eeca785',
    messagingSenderId: '1044637791712',
    projectId: 'ass5-q2',
    databaseURL: 'https://ass5-q2-default-rtdb.firebaseio.com',
    storageBucket: 'ass5-q2.appspot.com',
    iosClientId: '1044637791712-3pe23btlbo8bopcnbi86bgh6jdkgc8jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBik5WeXqfMsl14ZAN3TKru39vJR2xaB_E',
    appId: '1:1044637791712:ios:e880c341dfd36684eca785',
    messagingSenderId: '1044637791712',
    projectId: 'ass5-q2',
    databaseURL: 'https://ass5-q2-default-rtdb.firebaseio.com',
    storageBucket: 'ass5-q2.appspot.com',
    iosClientId: '1044637791712-lg6fvdigl0iqjitki9159m9ermh9n77t.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartRoom.RunnerTests',
  );
}
